--Find the total customers by countries
SELECT
Country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_genders
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_genders DESC

--Find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the average costs in each category?
SELECT 
category,
AVG(cost) AS Avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_cost DESC

--What is the total revenue generated for each category?
SELECT
dp.category,
SUM(fs.Sales_amount) AS Total_Revenue
FROM gold.dim_products dp
LEFT JOIN gold.fact_sales fs ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY Total_Revenue DESC


--Find total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC
-- What is the distribution of sold items across countries? 

SELECT
c.country,
SUM(f.sales_amount) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
	c.country
ORDER BY total_sold_items DESC
